In [ ]:
!pip install nashpy
!pip install axelrod

import nashpy as nash
import numpy as np


  Created wheel for nashpy: filename=nashpy-0.0.19-cp36-none-any.whl size=10815 sha256=d6909c24ecfeb21bc299fe36971ae33fba0a33d2bc78d2321a7895901cc07b1e
  Stored in directory: /root/.cache/pip/wheels/18/e9/56/2d04d01a6969d167f86d3afcb3d128c0b43d0d73ea471c835b
Successfully built nashpy
     |████████████████████████████████| 194kB 5.0MB/s 
     |████████████████████████████████| 358kB 12.9MB/s 
     |████████████████████████████████| 92kB 9.2MB/s 
ERROR: jupyter-console 5.2.0 has requirement prompt-toolkit<2.0.0,>=1.0.0, but you'll have prompt-toolkit 3.0.8 which is incompatible.
ERROR: ipython 5.5.0 has requirement prompt-toolkit<2.0.0,>=1.0.4, but you'll have prompt-toolkit 3.0.8 which is incompatible.
  Found existing installation: prompt-toolkit 1.0.18
    Uninstalling prompt-toolkit-1.0.18:
      Successfully uninstalled prompt-toolkit-1.0.18


In [ ]:
P1 = np.array([[-6,2],[-2,1]])
P2 = np.array([[-6,-2],[2,1]])
gm = nash.Game(P1,P2)
gm

Bi matrix game with payoff matrices:

Row player:
[[-6  2]
 [-2  1]]

Column player:
[[-6 -2]
 [ 2  1]]

In [ ]:
equilibria = gm.support_enumeration()
for eq in equilibria:
  print(eq)

(array([1., 0.]), array([0., 1.]))
(array([0., 1.]), array([1., 0.]))
(array([0.2, 0.8]), array([0.2, 0.8]))
