In [2]:
!pip install nashpy
!pip install axelrod

import nashpy as nash
import numpy as np


  Created wheel for nashpy: filename=nashpy-0.0.19-cp36-none-any.whl size=10815 sha256=ba194001d3796d605b8c0ea0ec6e9cc2fdca3f2b7aa069558b3fabaad138f115
  Stored in directory: /root/.cache/pip/wheels/18/e9/56/2d04d01a6969d167f86d3afcb3d128c0b43d0d73ea471c835b
Successfully built nashpy
     |████████████████████████████████| 194kB 4.6MB/s 
     |████████████████████████████████| 358kB 9.7MB/s 
     |████████████████████████████████| 92kB 6.3MB/s 
ERROR: jupyter-console 5.2.0 has requirement prompt-toolkit<2.0.0,>=1.0.0, but you'll have prompt-toolkit 3.0.8 which is incompatible.
ERROR: ipython 5.5.0 has requirement prompt-toolkit<2.0.0,>=1.0.4, but you'll have prompt-toolkit 3.0.8 which is incompatible.
  Found existing installation: prompt-toolkit 1.0.18
    Uninstalling prompt-toolkit-1.0.18:
      Successfully uninstalled prompt-toolkit-1.0.18


In [6]:
A = np.array([[8,0],[12,6]])
B = np.array([[8,12],[0,6]])
gm = nash.Game(A,B)
gm

Bi matrix game with payoff matrices:

Row player:
[[ 8  0]
 [12  6]]

Column player:
[[ 8 12]
 [ 0  6]]

In [7]:
equilibria = gm.support_enumeration()
for eq in equilibria:
  print(eq)

(array([0., 1.]), array([0., 1.]))
